### ISSUE TITLE
[BUG]: Security Vulnerability in share

### ISSUE THREAD

**Issue by simonkoeck** [simplifylabs/remark#25]
**Describe the bug**
CSRF (Cross Site Request Forgery) in share link

**To Reproduce**
If you copy a comment, remark generates a unique link with uuid of share (for example https://www.remark.surf/share?id=13f26979-43ac-4d9d-94aa-d9a51ccab0a5)

The vulnerable param here is id. If you change the id parameter for example to 13f26979-43ac-4d9d-94aa-d9a51ccab0a5/../../, you can manipulate the path of the api request. So for an attacker it could be possible to make any request from a victims account if the victim clicks on the manipulated share link. 

A possible solution to fix this vulnerability would be client side uuid validation.

**Comment by poeck** [comment]
So would uuid validation of the id parameter on the /share page fix this, or is validation later required too as the "remark" parameter is added there?

**Comment by simonkoeck** [comment]
I think the validation of the id parameter in the share page is enough, because this is the link which gets sent to the user. But it doesn't harm if you use the validation in browser extension too.

**Comment by poeck** [comment]
I see. I think directly sending the resolved url would still have that issue tho. For example : http://google.com/?remark=48129cd6-bff7-4dd0-83b1-9750bc3cd14f
