### ISSUE TITLE
[BUG]: Can't create new remark

### ISSUE THREAD

**Issue by simonkoeck** [simplifylabs/remark#29]
Cannot create new remark

I tried to create a remark on https://www.google.com/search?q=gulp&sxsrf=APq-WBuYtp4fzfyjddo0oa0OoB3i-0Z81g%3A1644050900129&source=hp&ei=1Dn-Yf-vBIHXkgWw9pTYCA&iflsig=AHkkrS4AAAAAYf5H5BTXRjn5KuAnZqT72PWdH7X-C50Z&ved=0ahUKEwj_6ZDvluj1AhWBq6QKHTA7BYsQ4dUDCAY&uact=5&oq=gulp&gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECcyBAgAEEMyBAgAEEMyBQguEIAEMgUIABCABDILCC4QgAQQxwEQ0QMyBQguEIAEMgUILhCABDIFCAAQgAQyBQgAEIAEOgcIIxDqAhAnOgoILhDHARDRAxBDOgsILhCABBDHARCjAjoICAAQBRAKEB46BwgjELECECc6BAguEAo6BAgAEAo6CgguEMcBENEDEApQzAJYlxNgtxRoAnAAeAGAAcYBiAGJB5IBAzAuNpgBAKABAbABCg&sclient=gws-wiz, but it doesn't work.

Somehow it works properly on other sites, it's just this url. Maybe url sanitization of the url parameters causes this bug. The console doesn't throw an error. A toast is shown with "Something unexpected happened".

Strangely enough it works with only the q param.

**Comment by poeck** [comment]
Fixed [here](https://github.com/simplifylabs/remark/commit/096b30ee354d6a7cb2331bc3a787dc477ff026c5). The url was just too long to for the originalURL column, so I increased it to 2000 chars.
